config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :autorizacao_voos
  resources :levantamento_riscos
  resources :acessorios
  resources :batteries
  resources :cadastro_unidade_rpas
  resources :cadastro_manutencao_rpas
  resources :relatorio_plano_de_voos
  resources :cadastro_equipe_rpas
  resources :plano_de_voos
  resources :cadastro_rpas
  root to: 'static_pages#index'

  # Using Devise for authentication
  devise_for :users,
    path_names: {
      sign_in: 'login', sign_out: 'logout',
      password: 'senha', confirmation: 'confirmar'
    },
    controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords'
    },
    skip: [:registrations]

  devise_scope :user do
    get "login", to: "users/sessions#new"
  end


  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :units, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :permissions, only: [:index, :new, :create, :edit, :update, :destroy]

end

app/models/cadastro_manutencao_rpa.rb
class CadastroManutencaoRpa < ApplicationRecord

  validates :nome_guarnicao,
            :manutencao_radio,
            :manutencao_bussola,
            :manutencao_acelerometro,
            :manutencao_giroscopio,
            :manutencao_firmware,
            :manutencao_helice,
            :manutencao_prot_helice,
            :manutencao_carcaca,
            :manutencao_controle_remoto,
            :manutencao_telemetria,
            :manutencao_gps,
            :manutencao_gimbal,
            :tipo_controladora_rpa,
            :outro_problema,
            presence: true
end

app/controllers/cadastro_manutencao_rpas_controller.rb
class CadastroManutencaoRpasController < ApplicationController
  before_action :set_cadastro_manutencao_rpa, only: [:show, :edit, :update, :destroy]

  # GET /cadastro_manutencao_rpas
  # GET /cadastro_manutencao_rpas.json
  def index
    @cadastro_manutencao_rpas = CadastroManutencaoRpa.all
  end

  # GET /cadastro_manutencao_rpas/1
  # GET /cadastro_manutencao_rpas/1.json
  def show
  end

  # GET /cadastro_manutencao_rpas/new
  def new
    @cadastro_rpas = CadastroRpa.all
    @cadastro_manutencao_rpa = CadastroManutencaoRpa.new
  end

  # GET /cadastro_manutencao_rpas/1/edit
  def edit
    @cadastro_rpas = CadastroRpa.all
  end

  # POST /cadastro_manutencao_rpas
  # POST /cadastro_manutencao_rpas.json
  def create
    @cadastro_manutencao_rpa = CadastroManutencaoRpa.new(cadastro_manutencao_rpa_params)

    respond_to do |format|
      if @cadastro_manutencao_rpa.save
        format.html { redirect_to @cadastro_manutencao_rpa, notice: 'Cadastro manutencao rpa was successfully created.' }
        format.json { render :show, status: :created, location: @cadastro_manutencao_rpa }
      else
        format.html { render :new }
        format.json { render json: @cadastro_manutencao_rpa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cadastro_manutencao_rpas/1
  # PATCH/PUT /cadastro_manutencao_rpas/1.json
  def update
    respond_to do |format|
      if @cadastro_manutencao_rpa.update(cadastro_manutencao_rpa_params)
        format.html { redirect_to @cadastro_manutencao_rpa, notice: 'Cadastro manutencao rpa was successfully updated.' }
        format.json { render :show, status: :ok, location: @cadastro_manutencao_rpa }
      else
        format.html { render :edit }
        format.json { render json: @cadastro_manutencao_rpa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadastro_manutencao_rpas/1
  # DELETE /cadastro_manutencao_rpas/1.json
  def destroy
    @cadastro_manutencao_rpa.destroy
    respond_to do |format|
      format.html { redirect_to cadastro_manutencao_rpas_url, notice: 'Cadastro manutencao rpa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastro_manutencao_rpa
      @cadastro_manutencao_rpa = CadastroManutencaoRpa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cadastro_manutencao_rpa_params
      params.require(:cadastro_manutencao_rpa).permit(:nome_guarnicao, :email, :endereco, :telefone, :modelo_rpa, :manutencao_radio, :manutencao_bussola, :manutencao_acelerometro, :manutencao_giroscopio, :manutencao_firmware, :manutencao_helice, :manutencao_prot_helice, :manutencao_carcaca, :manutencao_controle_remoto, :manutencao_telemetria, :manutencao_gps, :manutencao_gimbal, :tipo_controladora_rpa, :outro_problema, :id_usuario, :id_gup)
    end
end

app/helpers/cadastro_manutencao_rpas_helper.rb
module CadastroManutencaoRpasHelper
end

app/views/cadastro_manutencao_rpas/_form.html.erb
<%= form_for(cadastro_manutencao_rpa) do |f| %>
  <% if cadastro_manutencao_rpa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cadastro_manutencao_rpa.errors.count, "error") %> prohibited this cadastro_manutencao_rpa from being saved:</h2>

      <ul>
      <% cadastro_manutencao_rpa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <% render 'layouts/error_messages', object: f.object %>

    <!-- formulário do arquivo cadastro_manutencao_rpas
    OBS: sendo utilizado para a tabela de Manutenção da RPA-->

  <div class="form-group form-horizontal">
    <label for="">RPA:</label>
    <br>
    <%= f.select :cadastro_rpa_id, @cadastro_rpas.select {|rpa| rpa.id != f.object.id}.collect {|rpa| [rpa.matricula_rpa.titleize, rpa.id]}, {include_blank:'Selecione a Matrícula da RPA'}, {class:'form-control'} %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Nome do responsavel:</label>
    <br>
    <%= f.text_field :nome_guarnicao %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Manutenção do rádio:</label>
    <br>
    <%= f.text_field :manutencao_radio %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Manutenção da bússola:</label>
    <br>
    <%= f.text_field :manutencao_bussola %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Manutenção do Acelerometro:</label>
    <br>
    <%= f.text_field :manutencao_acelerometro %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Manutenção do giroscopio:</label>
    <br>
    <%= f.text_field :manutencao_giroscopio %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Manutenção da firmware:</label>
    <br>
    <%= f.text_field :manutencao_firmware %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Manutenção da helice:</label>
    <br>
    <%= f.text_field :manutencao_helice %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Manutenção do protetor da helice:</label>
    <br>
    <%= f.text_field :manutencao_prot_helice %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Manutenção da carcaça:</label>
    <br>
    <%= f.text_field :manutencao_carcaca %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Manutenção do controle remoto:</label>
    <br>
    <%= f.text_field :manutencao_controle_remoto %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Manutenção da Telemetria:</label>
    <br>
    <%= f.text_field :manutencao_telemetria %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Manutenção do GPS:</label>
    <br>
    <%= f.text_field :manutencao_gps %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Manutenção do Gimbal:</label>
    <br>
    <%= f.text_field :manutencao_gimbal %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Tipo de controladora do RPA:</label>
    <br>
    <%= f.text_field :tipo_controladora_rpa %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Outros problemas:</label>
    <br>
    <%= f.text_area :outro_problema %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cadastro_manutencao_rpas/edit.html.erb
<h1>Editando Cadastro de Manutenção RPA</h1>

<%= render 'form', cadastro_manutencao_rpa: @cadastro_manutencao_rpa %>

<%= link_to 'Mostrar', @cadastro_manutencao_rpa %> |
<%= link_to 'Voltar', cadastro_manutencao_rpas_path %>

app/views/cadastro_manutencao_rpas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Manutenção da RPA</h1>

<table class="table table-bordered table-hover table-condensed table-responsive">
  <thead>
    <tr>
      <th>Nome do responsavel</th>
      <th>Tipo de Controladora do RPA</th>
      <th>Outros Problemas</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cadastro_manutencao_rpas.each do |cadastro_manutencao_rpa| %>
      <tr>
        <td><%= cadastro_manutencao_rpa.nome_guarnicao %></td>
        <td><%= cadastro_manutencao_rpa.tipo_controladora_rpa %></td>
        <td><%= cadastro_manutencao_rpa.outro_problema %></td>

        <td><%= link_to 'Mostrar', cadastro_manutencao_rpa %></td>
        <td><%= link_to 'Editar', edit_cadastro_manutencao_rpa_path(cadastro_manutencao_rpa) %></td>
        <td><%= link_to 'Excluir', cadastro_manutencao_rpa, method: :delete, data: { confirm: 'Voce tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Nova Manutenção de RPA', new_cadastro_manutencao_rpa_path %>

app/views/cadastro_manutencao_rpas/new.html.erb
<h1>Novo Cadastro de Manutenção RPA</h1>

<%= render 'form', cadastro_manutencao_rpa: @cadastro_manutencao_rpa %>

<%= link_to 'Voltar', cadastro_manutencao_rpas_path %>

app/views/cadastro_manutencao_rpas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome do responsavel:</strong>
  <br>
  <%= @cadastro_manutencao_rpa.nome_guarnicao %>
</p>

<p>
  <strong>Manutenção do rádio:</strong>
  <br>
  <%= @cadastro_manutencao_rpa.manutencao_radio %>
</p>

<p>
  <strong>Manutenção da bússola:</strong>
  <br>
  <%= @cadastro_manutencao_rpa.manutencao_bussola %>
</p>

<p>
  <strong>Manutenção do Acelerometro:</strong>
  <br>
  <%= @cadastro_manutencao_rpa.manutencao_acelerometro %>
</p>

<p>
  <strong>Manutenção do giroscopio:</strong>
  <br>
  <%= @cadastro_manutencao_rpa.manutencao_giroscopio %>
</p>

<p>
  <strong>Manutenção da firmware:</strong>
  <br>
  <%= @cadastro_manutencao_rpa.manutencao_firmware %>
</p>

<p>
  <strong>Manutenção da helice:</strong>
  <br>
  <%= @cadastro_manutencao_rpa.manutencao_helice %>
</p>

<p>
  <strong>Manutenção do protetor da helice:</strong>
  <br>
  <%= @cadastro_manutencao_rpa.manutencao_prot_helice %>
</p>

<p>
  <strong>Manutenção da carcaça:</strong>
  <br>
  <%= @cadastro_manutencao_rpa.manutencao_carcaca %>
</p>

<p>
  <strong>Manutenção do controle remoto:</strong>
  <br>
  <%= @cadastro_manutencao_rpa.manutencao_controle_remoto %>
</p>

<p>
  <strong>Manutenção da Telemetria:</strong>
  <br>
  <%= @cadastro_manutencao_rpa.manutencao_telemetria %>
</p>

<p>
  <strong>Manutenção do GPS:</strong>
  <br>
  <%= @cadastro_manutencao_rpa.manutencao_gps %>
</p>

<p>
  <strong>Manutenção do Gimbal:</strong>
  <br>
  <%= @cadastro_manutencao_rpa.manutencao_gimbal %>
</p>

<p>
  <strong>Tipo de controladora do RPA:</strong>
  <br>
  <%= @cadastro_manutencao_rpa.tipo_controladora_rpa %>
</p>

<p>
  <strong>Outros problemas:</strong>
  <br>
  <%= @cadastro_manutencao_rpa.outro_problema %>
</p>

<%= link_to 'Editar', edit_cadastro_manutencao_rpa_path(@cadastro_manutencao_rpa) %> |
<%= link_to 'Voltar', cadastro_manutencao_rpas_path %>