config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :autorizacao_voos
  resources :levantamento_riscos
  resources :acessorios
  resources :batteries
  resources :cadastro_unidade_rpas
  resources :cadastro_manutencao_rpas
  resources :relatorio_plano_de_voos
  resources :cadastro_equipe_rpas
  resources :plano_de_voos
  resources :cadastro_rpas
  root to: 'static_pages#index'

  # Using Devise for authentication
  devise_for :users,
    path_names: {
      sign_in: 'login', sign_out: 'logout',
      password: 'senha', confirmation: 'confirmar'
    },
    controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords'
    },
    skip: [:registrations]

  devise_scope :user do
    get "login", to: "users/sessions#new"
  end


  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :units, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :permissions, only: [:index, :new, :create, :edit, :update, :destroy]

end

app/models/relatorio_plano_de_voo.rb
class RelatorioPlanoDeVoo < ApplicationRecord

  validates :condições_relevantes,
            :discrep_obser_missao,
            :discrep_anteriores_missao,
            :conclusao,
            presence: true
end

app/controllers/relatorio_plano_de_voos_controller.rb
class RelatorioPlanoDeVoosController < ApplicationController
  before_action :set_relatorio_plano_de_voo, only: [:show, :edit, :update, :destroy]

  # GET /relatorio_plano_de_voos
  # GET /relatorio_plano_de_voos.json
  def index
    @relatorio_plano_de_voos = RelatorioPlanoDeVoo.all
  end

  # GET /relatorio_plano_de_voos/1
  # GET /relatorio_plano_de_voos/1.json
  def show
  end

  # GET /relatorio_plano_de_voos/new
  def new
    @relatorio_plano_de_voo = RelatorioPlanoDeVoo.new
  end

  # GET /relatorio_plano_de_voos/1/edit
  def edit
  end

  # POST /relatorio_plano_de_voos
  # POST /relatorio_plano_de_voos.json
  def create
    @relatorio_plano_de_voo = RelatorioPlanoDeVoo.new(relatorio_plano_de_voo_params)

    respond_to do |format|
      if @relatorio_plano_de_voo.save
        format.html { redirect_to @relatorio_plano_de_voo, notice: 'Relatorio plano de voo was successfully created.' }
        format.json { render :show, status: :created, location: @relatorio_plano_de_voo }
      else
        format.html { render :new }
        format.json { render json: @relatorio_plano_de_voo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relatorio_plano_de_voos/1
  # PATCH/PUT /relatorio_plano_de_voos/1.json
  def update
    respond_to do |format|
      if @relatorio_plano_de_voo.update(relatorio_plano_de_voo_params)
        format.html { redirect_to @relatorio_plano_de_voo, notice: 'Relatorio plano de voo was successfully updated.' }
        format.json { render :show, status: :ok, location: @relatorio_plano_de_voo }
      else
        format.html { render :edit }
        format.json { render json: @relatorio_plano_de_voo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relatorio_plano_de_voos/1
  # DELETE /relatorio_plano_de_voos/1.json
  def destroy
    @relatorio_plano_de_voo.destroy
    respond_to do |format|
      format.html { redirect_to relatorio_plano_de_voos_url, notice: 'Relatorio plano de voo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relatorio_plano_de_voo
      @relatorio_plano_de_voo = RelatorioPlanoDeVoo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relatorio_plano_de_voo_params
      params.require(:relatorio_plano_de_voo).permit(:condições_relevantes, :discrep_obser_missao, :discrep_anteriores_missao, :conclusao, :id_pdv, :id_relatorio_voo)
    end
end

app/helpers/relatorio_plano_de_voos_helper.rb
module RelatorioPlanoDeVoosHelper
end

app/views/relatorio_plano_de_voos/_form.html.erb
<%= form_for(relatorio_plano_de_voo) do |f| %>
  <% if relatorio_plano_de_voo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(relatorio_plano_de_voo.errors.count, "error") %> prohibited this relatorio_plano_de_voo from being saved:</h2>

      <ul>
      <% relatorio_plano_de_voo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% render 'layouts/error_messages', object: f.object %>

  <!-- formulário do arquivo relatorio_plano_de_voos
  OBS: sendo utilizado para a tabela de Relatório de Vôo-->

  <div class="form-group form-horizontal">
    <label for="">Condições relevantes:</label>
    <br>
        <%= f.text_field :condições_relevantes %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Discrepância observada na missão:</label>
    <br>
      <%= f.text_field :discrep_obser_missao %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Discrepância anteriores da missão</label>
    <br>
      <%= f.text_field :discrep_anteriores_missao %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Conclusão:</label>
    <br>
      <%= f.text_field :conclusao %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/relatorio_plano_de_voos/edit.html.erb
<h1>Editando Relatório de Voo</h1>

<%= render 'form', relatorio_plano_de_voo: @relatorio_plano_de_voo %>

<%= link_to 'Mostrar', @relatorio_plano_de_voo %> |
<%= link_to 'Voltar', relatorio_plano_de_voos_path %>

app/views/relatorio_plano_de_voos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Relatórios de Vôo</h1>

<table  class="table table-bordered table-hover table-condensed table-responsive">
  <thead>
    <tr>
      <th>Condições relevantes</th>
      <th>Discrepância observada na missão</th>
      <th>Discrepância anteriores da missão</th>
      <th>Conclusão</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @relatorio_plano_de_voos.each do |relatorio_plano_de_voo| %>
      <tr>
        <td><%= relatorio_plano_de_voo.condições_relevantes %></td>
        <td><%= relatorio_plano_de_voo.discrep_obser_missao %></td>
        <td><%= relatorio_plano_de_voo.discrep_anteriores_missao %></td>
        <td><%= relatorio_plano_de_voo.conclusao %></td>
        <td><%= link_to 'Mostrar', relatorio_plano_de_voo %></td>
        <td><%= link_to 'Editar', edit_relatorio_plano_de_voo_path(relatorio_plano_de_voo) %></td>
        <td><%= link_to 'Excluir', relatorio_plano_de_voo, method: :delete, data: { confirm: 'Voce tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Relatorio de Vôo', new_relatorio_plano_de_voo_path %>

app/views/relatorio_plano_de_voos/new.html.erb
<h1>Novo Cadastro de Relatório de Vôo</h1>

<%= render 'form', relatorio_plano_de_voo: @relatorio_plano_de_voo %>

<%= link_to 'Voltar', relatorio_plano_de_voos_path %>

app/views/relatorio_plano_de_voos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Condições relevantes:</strong>
  <br>
  <%= @relatorio_plano_de_voo.condições_relevantes %>
</p>

<p>
  <strong>Discrepância observada na missão:</strong>
  <br>
  <%= @relatorio_plano_de_voo.discrep_obser_missao %>
</p>

<p>
  <strong>Discrepância anteriores da missão</strong>
  <br>
  <%= @relatorio_plano_de_voo.discrep_anteriores_missao %>
</p>

<p>
  <strong>Conclusão:</strong>
  <br>
  <%= @relatorio_plano_de_voo.conclusao %>
</p>


<%= link_to 'Editar', edit_relatorio_plano_de_voo_path(@relatorio_plano_de_voo) %> |
<%= link_to 'Voltar', relatorio_plano_de_voos_path %>