config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :autorizacao_voos
  resources :levantamento_riscos
  resources :acessorios
  resources :batteries
  resources :cadastro_unidade_rpas
  resources :cadastro_manutencao_rpas
  resources :relatorio_plano_de_voos
  resources :cadastro_equipe_rpas
  resources :plano_de_voos
  resources :cadastro_rpas
  root to: 'static_pages#index'

  # Using Devise for authentication
  devise_for :users,
    path_names: {
      sign_in: 'login', sign_out: 'logout',
      password: 'senha', confirmation: 'confirmar'
    },
    controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords'
    },
    skip: [:registrations]

  devise_scope :user do
    get "login", to: "users/sessions#new"
  end


  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :units, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :permissions, only: [:index, :new, :create, :edit, :update, :destroy]

end

app/models/cadastro_equipe_rpa.rb
class CadastroEquipeRpa < ApplicationRecord
  
  validates :nome,
            :tipo_licenca_certificado,
            :numero_licenca_certificado,
            :anexar_copia,
            :experiencia_pilito_observador,
            presence: true
end

app/controllers/cadastro_equipe_rpas_controller.rb
class CadastroEquipeRpasController < ApplicationController
  before_action :set_cadastro_equipe_rpa, only: [:show, :edit, :update, :destroy]

  # GET /cadastro_equipe_rpas
  # GET /cadastro_equipe_rpas.json
  def index
    @cadastro_equipe_rpas = CadastroEquipeRpa.all
  end

  # GET /cadastro_equipe_rpas/1
  # GET /cadastro_equipe_rpas/1.json
  def show
  end

  # GET /cadastro_equipe_rpas/new
  def new
    @plano_de_voos = PlanoDeVoo.all
    @cadastro_equipe_rpa = CadastroEquipeRpa.new
  end

  # GET /cadastro_equipe_rpas/1/edit
  def edit
    @plano_de_voos = PlanoDeVoo.all
  end

  # POST /cadastro_equipe_rpas
  # POST /cadastro_equipe_rpas.json
  def create
    @cadastro_equipe_rpa = CadastroEquipeRpa.new(cadastro_equipe_rpa_params)

    respond_to do |format|
      if @cadastro_equipe_rpa.save
        format.html { redirect_to @cadastro_equipe_rpa, notice: 'Cadastro equipe rpa was successfully created.' }
        format.json { render :show, status: :created, location: @cadastro_equipe_rpa }
      else
        format.html { render :new }
        format.json { render json: @cadastro_equipe_rpa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cadastro_equipe_rpas/1
  # PATCH/PUT /cadastro_equipe_rpas/1.json
  def update
    respond_to do |format|
      if @cadastro_equipe_rpa.update(cadastro_equipe_rpa_params)
        format.html { redirect_to @cadastro_equipe_rpa, notice: 'Cadastro equipe rpa was successfully updated.' }
        format.json { render :show, status: :ok, location: @cadastro_equipe_rpa }
      else
        format.html { render :edit }
        format.json { render json: @cadastro_equipe_rpa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cadastro_equipe_rpas/1
  # DELETE /cadastro_equipe_rpas/1.json
  def destroy
    @cadastro_equipe_rpa.destroy
    respond_to do |format|
      format.html { redirect_to cadastro_equipe_rpas_url, notice: 'Cadastro equipe rpa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cadastro_equipe_rpa
      @cadastro_equipe_rpa = CadastroEquipeRpa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cadastro_equipe_rpa_params
      params.require(:cadastro_equipe_rpa).permit(:nome, :tipo_licenca_certificado, :numero_licenca_certificado, :anexar_copia, :experiencia_pilito_observador, :id_usuario, :id_erpa)
    end
end

app/helpers/cadastro_equipe_rpas_helper.rb
module CadastroEquipeRpasHelper
end

app/views/cadastro_equipe_rpas/_form.html.erb
<%= form_for(cadastro_equipe_rpa) do |f| %>
  <% if cadastro_equipe_rpa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cadastro_equipe_rpa.errors.count, "error") %> prohibited this cadastro_equipe_rpa from being saved:</h2>

      <ul>
      <% cadastro_equipe_rpa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% render 'layouts/error_messages', object: f.object %>

  <!-- formulário do arquivo cadastro_equipe_rpas
  OBS: sendo utilizado para a tabela de piloto -->

  <div class="form-group form-horizontal">
    <label for="">Plano de Voo:</label>
    <br>
    <%= f.select :plano_de_voo_id, @plano_de_voos.select {|pdv| pdv.id != f.object.id}.collect {|pdv| [pdv.objetivo_operacao.titleize, pdv.id]}, {include_blank:'Selecione o Plano de voo'}, {class:'form-control'} %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Nome:</label>
    <br>
    <%= f.text_field :nome %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Tipo da licença do certificado</label>
    <br>
    <%= f.text_field :tipo_licenca_certificado %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Numero da licença do certificado:</label>
    <br>
    <%= f.number_field :numero_licenca_certificado %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Anexo da copia do certificado:</label>
    <br>
    <%= f.text_field :anexar_copia %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Experiência do piloto e observador:</label>
    <br>
    <%= f.text_area :experiencia_pilito_observador %>
  </div>

  <div class="form-group form-horizontal">
    <%= f.submit %>
  </div>
<% end %>

app/views/cadastro_equipe_rpas/edit.html.erb
<h1>Editando Cadastro de Piloto</h1>

<%= render 'form', cadastro_equipe_rpa: @cadastro_equipe_rpa %>

<%= link_to 'Mostrar', @cadastro_equipe_rpa %> |
<%= link_to 'Voltar', cadastro_equipe_rpas_path %>

app/views/cadastro_equipe_rpas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pilotos</h1>

<table class="table table-bordered table-hover table-condensed table-responsive">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Tipo da licença do certificado</th>
      <th>Numero da licença do certificado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cadastro_equipe_rpas.each do |cadastro_equipe_rpa| %>
      <tr>
        <td><%= cadastro_equipe_rpa.nome %></td>
        <td><%= cadastro_equipe_rpa.tipo_licenca_certificado %></td>
        <td><%= cadastro_equipe_rpa.numero_licenca_certificado %></td>
        <td><%= link_to 'Mostrar', cadastro_equipe_rpa %></td>
        <td><%= link_to 'Editar', edit_cadastro_equipe_rpa_path(cadastro_equipe_rpa) %></td>
        <td><%= link_to 'Excluir', cadastro_equipe_rpa, method: :delete, data: { confirm: 'Voce tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Piloto', new_cadastro_equipe_rpa_path %>

app/views/cadastro_equipe_rpas/new.html.erb
<h1>Novo Cadastro de Piloto</h1>

<%= render 'form', cadastro_equipe_rpa: @cadastro_equipe_rpa %>

<%= link_to 'Voltar', cadastro_equipe_rpas_path %>

app/views/cadastro_equipe_rpas/show.html.erb
<p id="notice"><%= notice %></p>

  <p>
    <strong>Nome:</strong>
    <br>
    <%= @cadastro_equipe_rpa.nome %>
  </p>

  <p>
    <strong>Tipo da licença do certificado:</strong>
    <br>
    <%= @cadastro_equipe_rpa.tipo_licenca_certificado %>
  </p>

  <p>
    <strong>Numero da licença do certificado:</strong>
    <br>
    <td><%= @cadastro_equipe_rpa.numero_licenca_certificado %></td>
  </p>

  <p>
    <strong>Anexo da copia do certificado:</strong>
    <br>
    <%= @cadastro_equipe_rpa.anexar_copia %>
  </p>

  <p>
    <strong>Experiência do piloto e observador:</strong>
    <br>
    <%= @cadastro_equipe_rpa.experiencia_pilito_observador %>
  </p>

<%= link_to 'Editar', edit_cadastro_equipe_rpa_path(@cadastro_equipe_rpa) %> |
<%= link_to 'Voltar', cadastro_equipe_rpas_path %>