config/routes.rb
Rails.application.routes.draw do

  resources :events
  resources :autorizacao_voos
  resources :levantamento_riscos
  resources :acessorios
  resources :batteries
  resources :cadastro_unidade_rpas
  resources :cadastro_manutencao_rpas
  resources :relatorio_plano_de_voos
  resources :cadastro_equipe_rpas
  resources :plano_de_voos
  resources :cadastro_rpas
  root to: 'static_pages#index'

  # Using Devise for authentication
  devise_for :users,
    path_names: {
      sign_in: 'login', sign_out: 'logout',
      password: 'senha', confirmation: 'confirmar'
    },
    controllers: {
      sessions: 'users/sessions',
      passwords: 'users/passwords'
    },
    skip: [:registrations]

  devise_scope :user do
    get "login", to: "users/sessions#new"
  end


  resources :users, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :units, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  resources :permissions, only: [:index, :new, :create, :edit, :update, :destroy]

end

app/models/acessorio.rb
class Acessorio < ApplicationRecord

    validates :nome,
              :cor,
              :descricao,
              presence: true

end

app/controllers/acessorios_controller.rb
class AcessoriosController < ApplicationController
  before_action :set_acessorio, only: [:show, :edit, :update, :destroy]

  # GET /acessorios
  # GET /acessorios.json
  def index
    @acessorios = Acessorio.all
  end

  # GET /acessorios/1
  # GET /acessorios/1.json
  def show
  end

  # GET /acessorios/new
  def new
    @cadastro_rpas = CadastroRpa.all
    @acessorio = Acessorio.new
  end

  # GET /acessorios/1/edit
  def edit
    @cadastro_rpas = CadastroRpa.all
  end

  # POST /acessorios
  # POST /acessorios.json
  def create
    @acessorio = Acessorio.new(acessorio_params)

    respond_to do |format|
      if @acessorio.save
        format.html { redirect_to @acessorio, notice: 'Acessorio was successfully created.' }
        format.json { render :show, status: :created, location: @acessorio }
      else
        format.html { render :new }
        format.json { render json: @acessorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acessorios/1
  # PATCH/PUT /acessorios/1.json
  def update
    respond_to do |format|
      if @acessorio.update(acessorio_params)
        format.html { redirect_to @acessorio, notice: 'Acessorio was successfully updated.' }
        format.json { render :show, status: :ok, location: @acessorio }
      else
        format.html { render :edit }
        format.json { render json: @acessorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acessorios/1
  # DELETE /acessorios/1.json
  def destroy
    @acessorio.destroy
    respond_to do |format|
      format.html { redirect_to acessorios_url, notice: 'Acessorio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acessorio
      @acessorio = Acessorio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def acessorio_params
      params.require(:acessorio).permit(:nome, :cor, :descricao)
    end
end

app/helpers/acessorios_helper.rb
module AcessoriosHelper
end

app/views/acessorios/_form.html.erb
<%= form_for(acessorio) do |f| %>
  <% if acessorio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(acessorio.errors.count, "error") %> prohibited this acessorio from being saved:</h2>

      <ul>
      <% acessorio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% render 'layouts/error_messages', object: f.object %>

  <!-- formulário do arquivo acessorios -->

  <div class="form-group form-horizontal">
    <label for="">RPA:</label>
    <br>
    <%= f.select :cadastro_rpa_id, @cadastro_rpas.select {|rpa| rpa.id != f.object.id}.collect {|rpa| [rpa.matricula_rpa.titleize, rpa.id]}, {include_blank:'Selecione a Matrícula da RPA'}, {class:'form-control'} %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Nome do acessório:</label>
    <br>
    <%= f.text_field :nome %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Modelo do acessório:</label>
    <br>
    <%= f.text_field :cor %>
  </div>

  <div class="form-group form-horizontal">
    <label for="">Descrição do acessório:</label>
    <br>
    <%= f.text_area :descricao %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/acessorios/edit.html.erb
<h1>Editando Acessório</h1>

<%= render 'form', acessorio: @acessorio %>

<%= link_to 'Mostrar', @acessorio %> |
<%= link_to 'Voltar', acessorios_path %>

app/views/acessorios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Acessórios</h1>

<table class="table table-bordered table-hover table-condensed table-responsive">
  <thead>
    <tr>
      <th>Nome do acessório</th>
      <th>Modelo do acessório</th>
      <th>Descrição do acessório</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @acessorios.each do |acessorio| %>
      <tr>
        <td><%= acessorio.nome %></td>
        <td><%= acessorio.cor %></td>
        <td><%= acessorio.descricao %></td>
        <td><%= link_to 'Mostrar', acessorio %></td>
        <td><%= link_to 'Editar', edit_acessorio_path(acessorio) %></td>
        <td><%= link_to 'Excluir', acessorio, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo Acessório', new_acessorio_path %>

app/views/acessorios/new.html.erb
<h1>Novo Acessório</h1>

<%= render 'form', acessorio: @acessorio %>

<%= link_to 'Voltar', acessorios_path %>

app/views/acessorios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome do acessório:</strong>
  <br>
  <%= @acessorio.nome %>
</p>

<p>
  <strong>Modelo do acessório:</strong>
  <br>
  <%= @acessorio.cor %>
</p>

<p>
  <strong>Descrição do acessório:</strong>
  <br>
  <%= @acessorio.descricao %>
</p>

<%= link_to 'Editar', edit_acessorio_path(@acessorio) %> |
<%= link_to 'Voltar', acessorios_path %>